version: '3'

services:
  api:
    build: weather-api/
    depends_on:
      - 'database'
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: myDGhrrBLRq5kKg7c
      DOCKERIZED: 1
      POSTGRES_DB: weather
    volumes:
      - './weather-api:/src/app'
      - '/src/app/node_modules'

    ports: 
      - '3001:3001'

  client:
    build: weather-client/
    depends_on:
      - 'database'
      - 'api'
    volumes:
      - './weather-client:/web'
      - '/web/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true

  database:
    build: database/
    restart: always
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: myDGhrrBLRq5kKg7c
      POSTGRES_DB: weather
      
networks:
  weather-network:
    name: weather-network